// AYTest_TextureLoaderLoose.cpp — dev raw-reference mode: TextureLoader
// must decode loose png/jpg/... (AY_TEXTURE_LOOSE_FORMATS) as single-level
// RGBA8. The 4x4 red PNG fixture is generated by d:/tmp/gen_png.pl (zlib
// stored block, no external tooling needed at test time).

#include "AYResource/Loader/TextureLoader.h"
#include "AYResource/assetsDefs/ITexture.h"
#include "AYResource/assetsImpl/Texture.h"
#include "AYTest.h"

#include <AYIO/File.h>

#include <cstring>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <string>

using namespace ayt::resource;

namespace {

// 4x4 pure-red RGBA PNG, 136 bytes (stb_image-decodable)
static const unsigned char k4x4RedPng[] = {
    0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A, 0x00, 0x00, 0x00, 0x0D,
    0x49, 0x48, 0x44, 0x52, 0x00, 0x00, 0x00, 0x04, 0x00, 0x00, 0x00, 0x04,
    0x08, 0x06, 0x00, 0x00, 0x00, 0xA9, 0xF1, 0x9E, 0x7E, 0x00, 0x00, 0x00,
    0x4F, 0x49, 0x44, 0x41, 0x54, 0x78, 0x01, 0x01, 0x44, 0x00, 0xBB, 0xFF,
    0x00, 0xFF, 0x00, 0x00, 0xFF, 0xFF, 0x00, 0x00, 0xFF, 0xFF, 0x00, 0x00,
    0xFF, 0xFF, 0x00, 0x00, 0xFF, 0x00, 0xFF, 0x00, 0x00, 0xFF, 0xFF, 0x00,
    0x00, 0xFF, 0xFF, 0x00, 0x00, 0xFF, 0xFF, 0x00, 0x00, 0xFF, 0x00, 0xFF,
    0x00, 0x00, 0xFF, 0xFF, 0x00, 0x00, 0xFF, 0xFF, 0x00, 0x00, 0xFF, 0xFF,
    0x00, 0x00, 0xFF, 0x00, 0xFF, 0x00, 0x00, 0xFF, 0xFF, 0x00, 0x00, 0xFF,
    0xFF, 0x00, 0x00, 0xFF, 0xFF, 0x00, 0x00, 0xFF, 0x3C, 0x40, 0x1F, 0xE1,
    0x52, 0xED, 0xFF, 0xA2, 0x00, 0x00, 0x00, 0x00, 0x49, 0x45, 0x4E, 0x44,
    0xAE, 0x42, 0x60, 0x82,
};

const std::string kRoot = "ayres_texture_loose_tmp";

void cleanup()
{
    std::error_code ec;
    std::filesystem::remove_all(kRoot, ec);
}

bool writePng(const std::string& path)
{
    std::filesystem::create_directories(std::filesystem::path(path).parent_path());
    std::ofstream out(path, std::ios::binary | std::ios::trunc);
    if (!out) {
        return false;
    }
    out.write(reinterpret_cast<const char*>(k4x4RedPng), sizeof(k4x4RedPng));
    return static_cast<bool>(out);
}

} // namespace

TEST_SUITE(TextureLoaderLooseTests)

TEST_CASE(canLoad_matrix_follows_loose_gate)
{
    TextureLoader loader;
    CHECK(loader.canLoad("texture.aytex") == true);
    CHECK(loader.canLoad("textures/diffuse_d.aytex") == true);
    CHECK(loader.canLoad("texture.aymesh") == false);
#if defined(AY_TEXTURE_LOOSE_FORMATS)
    CHECK(loader.canLoad("texture.png") == true);
    CHECK(loader.canLoad("textures/foo_d.png") == true);
    CHECK(loader.canLoad("photo.jpg") == true);
    CHECK(loader.canLoad("photo.jpeg") == true);
    CHECK(loader.canLoad("scene.bmp") == true);
    CHECK(loader.canLoad("logo.tga") == true);
    CHECK(loader.canLoad("texture.TGA") == true);   // case-insensitive
#else
    CHECK(loader.canLoad("texture.png") == false);
    CHECK(loader.canLoad("photo.jpg") == false);
#endif
}

TEST_CASE(load_loose_png_decodes_single_level_rgba8)
{
#if !defined(AY_TEXTURE_LOOSE_FORMATS)
    return;  // gated off in this config — nothing to test
#else
    cleanup();
    const std::string path = kRoot + "/assets/textures/red_d.png";
    CHECK(writePng(path));

    TextureLoader loader;
    auto resource = loader.load(path);
    CHECK(resource != nullptr);

    auto texture = std::dynamic_pointer_cast<Texture>(resource);
    CHECK(texture != nullptr);
    CHECK(texture->getWidth() == 4);
    CHECK(texture->getHeight() == 4);
    CHECK(texture->getFormat() == TextureFormat::RGBA8);
    CHECK(texture->getMipmapCount() == 1);
    CHECK(texture->getMipmapSize(0) == 4 * 4 * 4);

    const UInt8* px = texture->getMipmapData(0);
    CHECK(px != nullptr);
    for (size_t i = 0; i < 16; i++) {
        CHECK(px[i * 4 + 0] == 255);  // R
        CHECK(px[i * 4 + 1] == 0);    // G
        CHECK(px[i * 4 + 2] == 0);    // B
        CHECK(px[i * 4 + 3] == 255);  // A
    }
    cleanup();
#endif
}

TEST_CASE(load_loose_missing_file_returns_null)
{
#if !defined(AY_TEXTURE_LOOSE_FORMATS)
    return;
#else
    TextureLoader loader;
    auto resource = loader.load(kRoot + "/does_not_exist.png");
    CHECK(resource == nullptr);
#endif
}

TEST_CASE(load_aytex_still_works_alongside_loose)
{
    Texture original;
    original.createSolidColor(2, 2, 10, 20, 30, 255);

    std::vector<UInt8> binaryData;
    CHECK(original.saveToBinary(binaryData) == true);

    cleanup();
    const std::string path = kRoot + "/solid.aytex";
    std::filesystem::create_directories(kRoot);
    {
        std::ofstream out(path, std::ios::binary | std::ios::trunc);
        out.write(reinterpret_cast<const char*>(binaryData.data()),
                  static_cast<std::streamsize>(binaryData.size()));
        // out must be closed before the loader reads: an unflushed ofstream
        // leaves a 0-byte file on disk (loader reads a fresh FILE*).
    }

    TextureLoader loader;
    auto resource = loader.load(path);
    CHECK(resource != nullptr);

    auto texture = std::dynamic_pointer_cast<Texture>(resource);
    CHECK(texture != nullptr);
    if (texture == nullptr) {
        cleanup();
        return;
    }
    CHECK(texture->getWidth() == 2);
    CHECK(texture->getHeight() == 2);
    CHECK(texture->getFormat() == TextureFormat::RGBA8);
    cleanup();
}

TEST_SUITE_END
